# Generated by Django 4.0.6 on 2022-07-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='soap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('sprice', models.IntegerField()),
                ('sdes', models.CharField(max_length=100)),
            ],
        ),
    ]
