# Generated by Django 4.0.6 on 2022-07-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alpha'),
    ]

    operations = [
        migrations.CreateModel(
            name='paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('sprice', models.IntegerField()),
                ('sdes', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='alpha',
        ),
    ]
